import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import NavBB from "@/componentes/navBB/NavBB";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBB></NavBB>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// app/layout.tsx
// import { Providers } from "./providers";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
